ALTER TABLE members ADD COLUMN password_hash TEXT;
ALTER TABLE members ADD COLUMN failed_logins INTEGER NOT NULL DEFAULT 0;
ALTER TABLE members ADD COLUMN locked_until TEXT;
ALTER TABLE members ADD COLUMN phone TEXT NOT NULL DEFAULT '';
ALTER TABLE members ADD COLUMN contact_email TEXT NOT NULL DEFAULT '';
ALTER TABLE members ADD COLUMN marketing_sms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE members ADD COLUMN marketing_email INTEGER NOT NULL DEFAULT 0;
ALTER TABLE members ADD COLUMN terms_agreed_at TEXT;
