'use client';
import {useEffect,useMemo,useState} from 'react';
import {Search,ShoppingBag,Heart,UserRound,House,Grid2X2,ArrowUpRight,ArrowRight,Minus,Plus,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {money,type Product} from './catalog';
type CartItem={product:Product;color:string;qty:number};
export default function Shop({initialProducts}:{initialProducts:Product[]}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('전체'),[items,setItems]=useState<Product[]>(initialProducts),[selected,setSelected]=useState<Product|null>(null),[color,setColor]=useState(''),[cartOpen,setCartOpen]=useState(false),[cart,setCart]=useState<CartItem[]>([]),[wish,setWish]=useState<string[]>([]),[toast,setToast]=useState('');
 useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem('somi_cart')||'[]'));setWish(JSON.parse(localStorage.getItem('somi_wish')||'[]'))}catch{}if(new URLSearchParams(location.search).get('view')==='cart')setCartOpen(true)},[]);
 useEffect(()=>{localStorage.setItem('somi_cart',JSON.stringify(cart))},[cart]);useEffect(()=>{localStorage.setItem('somi_wish',JSON.stringify(wish))},[wish]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();void Promise.resolve(context.registerTool({name:'filter_somimall_products',title:'소미몰 상품 찾기',description:'카테고리와 검색어로 소미몰 상품을 필터링합니다.',inputSchema:{type:'object',properties:{category:{type:'string',enum:['전체','상의','하의','아우터','가방','신발']},query:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input:unknown){const v=(input??{}) as {category?:string;query?:string};if(v.category)setCategory(v.category);setQuery(v.query??'');return {status:'filtered',category:v.category??'전체',query:v.query??''}}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[]);
 const filtered=useMemo(()=>items.filter(p=>(category==='전체'||p.category===category)&&`${p.name} ${p.brand}`.toLowerCase().includes(query.toLowerCase())),[items,category,query]);const count=cart.reduce((n,x)=>n+x.qty,0);const total=cart.reduce((n,x)=>n+x.product.price*x.qty,0);
 function openProduct(p:Product){setSelected(p);setColor(p.colors[0])}function add(){if(!selected)return;setCart(v=>{const i=v.findIndex(x=>x.product.id===selected.id&&x.color===color);if(i<0)return[...v,{product:selected,color,qty:1}];return v.map((x,n)=>n===i?{...x,qty:x.qty+1}:x)});setSelected(null);setToast('장바구니에 담았습니다.');setTimeout(()=>setToast(''),1800)}function qty(i:number,d:number){setCart(v=>v.map((x,n)=>n===i?{...x,qty:Math.max(0,x.qty+d)}:x).filter(x=>x.qty>0))}
 return <><div className="topline">나의 취향이 모이는 곳, 소미몰 <ArrowUpRight size={14}/></div><header className="header"><a className="logo" href="/">somi<span>mall</span><i/></a><div className="search"><Search size={20}/><input aria-label="상품 검색" placeholder="지금 찾고 있는 스타일은?" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="header-actions"><a href="/account" aria-label="로그인"><UserRound/></a><button onClick={()=>setWish(wish)} aria-label="찜"><Heart/></button><button className="cart-icon" onClick={()=>setCartOpen(true)} aria-label={`장바구니 ${count}개`}><ShoppingBag/>{count>0&&<i>{count}</i>}</button></div></header><main className="shell"><nav className="mainnav"><b>추천</b><button onClick={()=>setCategory('전체')}>신상품</button><button onClick={()=>setCategory('전체')}>소미 셀렉트</button><span>FIND YOUR EVERYDAY</span></nav><section className="intro"><div><span className="eyebrow">SOMI EDIT / 01</span><h1>매일의 나를,<br/>조금 더 좋아하게.</h1><p>가볍게 걸치고, 자연스럽게 나답게.</p><button onClick={()=>document.getElementById('catalog')?.scrollIntoView({behavior:'smooth'})}>셀렉션 만나기 <ArrowRight size={17}/></button></div><div className="intro-type">hello,<br/><em>new mood.</em><span>2026 COLLECTION</span></div></section><div className="categories">{['전체','상의','하의','아우터','가방','신발'].map(c=><button key={c} onClick={()=>setCategory(c)} className={category===c?'selected':''}>{c}</button>)}</div><section id="catalog"><div className="section-head"><div><span className="eyebrow">JUST FOR YOU</span><h2>오늘, 눈여겨볼 스타일</h2></div><span>{filtered.length}개의 상품</span></div><div className="product-grid">{filtered.map(p=><article key={p.id}><button className="product-image" onClick={()=>openProduct(p)} aria-label={`${p.name} 상세 보기`}><img src={p.image} alt={p.name}/><span>소미 셀렉트</span></button><button className={`heart ${wish.includes(p.id)?'active':''}`} onClick={()=>setWish(v=>v.includes(p.id)?v.filter(id=>id!==p.id):[...v,p.id])} aria-label={`${p.name} 찜`}><Heart size={21} fill={wish.includes(p.id)?'currentColor':'none'}/></button><button className="product-info" onClick={()=>openProduct(p)}><b>{p.brand}</b><h3>{p.name}</h3><div className="price"><strong>{Math.round((1-p.price/p.original)*100)}%</strong><b>{money(p.price)}</b><del>{money(p.original)}</del></div><small>샘플 상품 · 판매 준비 중</small></button></article>)}</div>{!filtered.length&&<p className="empty">검색한 상품이 없어요.</p>}</section><footer><a className="logo" href="/">somimall<i/></a><p>취향을 발견하는 작은 즐거움.</p><p>현재 상품과 가격은 샘플이며 실제 결제는 제공하지 않습니다.</p><a href="/admin">운영자 관리</a><small>© 2026 SOMIMALL</small></footer></main><nav className="bottomnav"><a href="/"><House/>홈</a><button onClick={()=>document.querySelector('.categories')?.scrollIntoView({behavior:'smooth'})}><Grid2X2/>카테고리</button><button onClick={()=>setWish(wish)}><Heart/>찜 {wish.length||''}</button><button onClick={()=>setCartOpen(true)}><ShoppingBag/>장바구니 {count||''}</button><a href="/account"><UserRound/>마이</a></nav>
 <Dialog open={Boolean(selected)} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="product-dialog">{selected&&<><img src={selected.image} alt={selected.name}/><div className="detail"><DialogHeader><DialogTitle>{selected.name}</DialogTitle><DialogDescription>{selected.brand} · 샘플 상품</DialogDescription></DialogHeader><div className="price big"><strong>{Math.round((1-selected.price/selected.original)*100)}%</strong><b>{money(selected.price)}원</b></div><p>매일 편하게 손이 가는 소미몰 셀렉션입니다. 상세 소재와 치수는 추후 등록됩니다.</p><b>색상</b><div className="options">{selected.colors.map(c=><button className={color===c?'selected':''} onClick={()=>setColor(c)} key={c}>{c}</button>)}</div><button className="buy" onClick={add}>장바구니 담기</button></div></>}</DialogContent></Dialog>
 <Dialog open={cartOpen} onOpenChange={setCartOpen}><DialogContent className="cart-dialog"><DialogHeader><DialogTitle>장바구니</DialogTitle><DialogDescription>{count}개의 상품이 담겨 있어요.</DialogDescription></DialogHeader>{cart.length===0?<p className="empty">장바구니가 비어 있어요.</p>:<>{cart.map((x,i)=><div className="cart-row" key={`${x.product.id}-${x.color}`}><img src={x.product.image} alt=""/><div><b>{x.product.name}</b><small>{x.color}</small><strong>{money(x.product.price*x.qty)}원</strong></div><div className="stepper"><button onClick={()=>qty(i,-1)} aria-label="수량 줄이기"><Minus/></button><span>{x.qty}</span><button onClick={()=>qty(i,1)} aria-label="수량 늘리기"><Plus/></button><button onClick={()=>setCart(v=>v.filter((_,n)=>n!==i))} aria-label="삭제"><Trash2/></button></div></div>)}<div className="cart-total"><span>총 상품 금액</span><b>{money(total)}원</b></div><button className="buy" disabled>결제 기능 준비 중</button></>}</DialogContent></Dialog>{toast&&<div className="toast">{toast}</div>}</>;
}
