'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,Heart,ShoppingBag,Truck} from 'lucide-react';
import {money,type Product} from '@/app/catalog';
export default function ProductDetail({product,recommendations}:{product:Product;recommendations:Product[]}){
 const [color,setColor]=useState(product.colors[0]||'기본');const [tab,setTab]=useState('상품정보');const [saved,setSaved]=useState(false);const status=product.saleStatus??(product.sample?'판매 준비':'판매중');const discount=Math.max(0,Math.round((1-product.price/product.original)*100));useEffect(()=>{try{const ids=JSON.parse(localStorage.getItem('somi_viewed')||'[]').filter((id:string)=>id!==product.id);localStorage.setItem('somi_viewed',JSON.stringify([product.id,...ids].slice(0,12)))}catch{}},[product.id]);
 function add(){if(status!=='판매중')return;const old=JSON.parse(localStorage.getItem('somi_cart')||'[]');localStorage.setItem('somi_cart',JSON.stringify([...old,{product,color,qty:1}]));location.href='/cart'}
 return <main className="detail-page"><header className="detail-top"><a href="/"><ArrowLeft/></a><b>상품정보</b><span><a href="/wishlist"><Heart/></a><a href="/cart"><ShoppingBag/></a></span></header><img className="detail-hero" src={product.image} alt={product.name}/><section className="detail-summary"><small>{product.brand} · {status}</small><h1>{product.name}</h1><div className="detail-price"><strong>{discount}%</strong><b>{money(product.price)}원</b><del>{money(product.original)}원</del></div><p>매일 입기 좋은 소미몰 셀렉트 아이템이에요. 편안한 핏과 활용도 높은 디자인으로 준비했습니다.</p><div className="delivery"><Truck size={19}/><span><b>무료배송</b><br/>주문 후 2~3일 내 출고 예정</span></div><b>색상 선택</b><div className="options">{product.colors.map(c=><button key={c} className={c===color?'selected':''} onClick={()=>setColor(c)}>{c}</button>)}</div></section><nav className="detail-tabs">{['상품정보','리뷰 23','사이즈','문의'].map(x=><button className={tab===x?'selected':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><section className="detail-body">{tab==='상품정보'&&<><h2>함께 코디하면 좋은 상품</h2><div className="recommend-grid">{recommendations.map(p=><a href={`/product/${p.id}`} key={p.id}><img src={p.image} alt=""/><b>{p.name}</b><span>{money(p.price)}원</span></a>)}</div><div className="notice"><h2>구매 전 확인해 주세요</h2><p>상품 이미지는 모니터 환경에 따라 색상이 다르게 보일 수 있습니다. 자세한 배송·교환·반품 안내는 주문 전 확인해 주세요.</p></div></>}{tab==='리뷰 23'&&<div className="notice"><h2>구매자 리뷰</h2><p>“핏이 예쁘고 데일리로 입기 좋아요.”</p><p>“색감이 화면과 같아요. 만족합니다.”</p></div>}{tab==='사이즈'&&<div className="notice"><h2>사이즈 안내</h2><p>상세 치수는 상품별로 달라요. 평소 착용하시는 사이즈를 기준으로 선택해 주세요.</p></div>}{tab==='문의'&&<div className="notice"><h2>상품 문의</h2><p>상품 관련 문의는 준비 중입니다.</p></div>}</section><footer className="purchase-bar"><button onClick={()=>setSaved(!saved)} className={saved?'liked':''}><Heart fill={saved?'currentColor':'none'}/></button><button disabled={status!=='판매중'} onClick={add}>{status==='판매중'?'장바구니 담기':status}</button></footer></main>;
}
